project:
  type: book
  output-dir: docs

book:
  title: "Improving Inventory Management Through Simulation"
  subtitle: "An Introduction for Spare Parts Business"
  reader-mode: true
  author: "Alexander Schniertshauer"
  date: "2024-01-02"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  
cover-image: Teilelager.jpg
favicon: Teilelager.jpg

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    pdfengine: xelatex
    mainfont: "Arial"

editor: visual

