# Preface {.unnumbered}

This is the website for "Simulation Techniques for Spare Parts Business", a book that will teach you how to apply simulation techniques in order to evaluate and improve inventory management for spare parts. You may ask yourselves why spare parts? A first, and maybe the simplest, answer is: I have worked for 35 years in that field and I know that the challenging nature of that business makes it a master discipline for inventory management. I hope my experience will add valuable insights and practical flavour when we discuss inventory management and simulation. The second answer can be found in the foreword of a seminal book on the management of service parts. Here the authors [@altay_litteral_2011] state that

> "everyone involved in the project agrees on two things: first, the management of spare parts is important because of its prevailing nature and magnitude and second, the problems associated with the management of spare parts are complex and really very hard."

There is little to add to that statement. The complexity of spare parts business, especially in the area of inventory management, requires the use of IT solutions that are in itself complicate to install and handle. And it is exactly at this point where simulations should play an important role for management: Simulation modeling may help to solve real-world problems efficiently annd robustely. It provides an important element in the OR toolset which is easily understood and communicated. In inventory management simulations inform about the impacts of different inventory policies, parameter settings, usage scenarios, etc.

Despite all these advantages, at least from my experience, simulations are seldom used regularly and systematically. Why is that? Part of the answer may be that inventory management staff and parts management lack an understanding how simulation can be practically applied, what questions need to be asked, and what tools are available to implement it.

Based on the usage of R this book hopefully helps to close the gap between theory and practice. It wants to encourage a more widespread use of simulations in daily business practice, and to serve as a starting point for your own journey.

In this book you will get acquainted with real-life characteristics of spare parts data (like demand and order patterns). You'll learn how to explore, visualize, and classify these demand patterns . You will become familiar with different approaches to simulate parts demands and get a feeling for the pitfalls and shortcomings of these approaches. You' ll learn how to simulate the impact of various forecasting methods, policies for safety stock and ordering.

The book requires a basic knowledge of R and the tidyverse. A familiarity with fundamental principles and methods of inventory management is also a must.

This website is (and will always be) free to use, and is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 License. If you'd like a physical copy of the book, you can order it from MyPublisher.

## About the Author {.unnumbered}


Professionally, Alexander Schniertshauer offers a wealth of international experience and extensive business exposure to a variety of functions and activities within the automotive industry. Since 2007, he has served as a strategic advisor to major global automotive players. Prior to that he has build,within Daimler-Benz, a career spanning over two decades. In diverse roles, he has steered, as Vice President of Technical Service, the global service operations for Mercedes-Benz vehicles, managed global After Sales Marketing, and headed Mercedes-Benz Russia. Additionally, he served on the supervisory boards of various Daimler affiliates.

Beyond his professional endeavors, Alexander is deeply engaged in exploring how analytical approaches and machine learning can revolutionize the service and parts industry, leveraging extensive data resources to gain a competitive edge. A passionate enthusiast of the R programming language, he continually seeks out new possibilities and tools within the R ecosystem.

Outside of work, Alexander loves to read (mostly about history) and is currently learning Hebrew. He also finds joy in traveling, hiking, skiing, and cherishing quality time with his family.


## Acknowledgements {.unnumbered}

"Simulation Techniques for Spare Parts Business" is hosted by <https://www.netlify.com> as part of their support of open source software and communities.
